= Reply to and Forward Messages

== Set Preferences for Email Replies

To reply to the message in the same format it is received, select
Reply/Forward using format of the original message. This ensures that the
recipient gets the message in the most readable format.

  . Go to the *Preferences>Mail* page, *Composing Messages* section.

  . To reply to the message in the same format it is received, select
    *Reply/Forward using format of the original message*.

  . Select whether to include the original text in your reply message. If
    you are including the original message:

    * Select whether to mark the previous responses with a character or
      include the original details in the header (The To, From, and Subject
      fields). You can also include the original message as an attachment.

    * If you want to prefix the previous responses, select either the angle
      bracket (>) or pipe (|).

  . Click *Save*.

== Replying to Email Messages

You can reply to the sender of a message or to the sender and all
recipients.

By default, when you reply to a message, the original message is included
in the body, but the original attachments are not. You can also decide to
prefix each response in the message to track the different replies.

For example, each reply within the message is marked with an angle bracket
(>). The most recent reply has one > before each line, the reply before
that has two (>>), before that three (>>>):

  > Previous message
  > > Message before previous message
  > > > And so forth

=== Reply to a Message

  . Select the email you want to reply to.

  . Click *Reply* or *Reply to All* in the toolbar. A new compose window is
    displayed with the address(es) in the header and the original message in
    the body.
+
If you view message in the Conversation view, you can click reply at the
bottom of the message

  . Type your reply.

  . Click *Options* on the toolbar and select an option if you want to
    change how the original message is included in the reply.

  . Click *Send*.

[NOTE]
If you add your signature automatically to your messages, it is placed in
the message according to your preference settings.

== Set Preferences for Forwarded Email

When you forward an email you can choose how to handle the original text
when forwarding an email message.

  . Go to the *Preferences>Mail* page, *Composing Messages* section.

  . If you want to prefix the original message, select either the angle
    bracket (>) or pipe (|)

[NOTE]
If you have selected a prefix for reply messages, you must use the same
prefix for both replies and forwarded messages.

== Forwarding Email Messages

You can forward an email message to someone else. Forwarding a message
includes all file attachments.

  . Select the email you want to forward.

  . Click *Forward* on the toolbar. The text of the forwarded message appears in the body of the compose page, unless you have set your preferences to forward messages as attachments.

  . Enter addressees.

  . Click *Send*.

== Automatically Forwarding Messages You Receive

You can configure your email preferences to automatically forward a
messages you receive to another account.

  . Go to the *Preferences>Mail* page.

  . In the *Receiving Messages>Message Arrival* section, *Forward a copy
    to:* text box enter the email address where email messages should be
    sent.

  . If do not want the messages saved in your mailbox, select *Don’t keep a
    local copy of messages*.

  . Click *Save*.

== Forward a Message as the Originator

You can forward an existing message as if you are the originator of the
message. The forwarded notice is not added to the subject field and the
header information shows you are the originator.

  . Right-click on the message and select *Edit as New*.

  . Address the message, remove existing address if necessary.

  . Click *Send*.

== Forward a Message as a Redirected Message

Redirecting a message lets you send an email message you received as if the
original author sent the message. Redirect a message instead of forwarding
it makes it easier for the recipient to reply to the original sender.

  . Right-click on the message and select *Redirect*.

  . In the *Redirect* text box, enter the recipient(s) address.

  . Click *OK*.
