= Retrieving Mail From Other Accounts

== Accessing Your External Accounts

Instead of logging on to each of your external email accounts, you can
retrieve your accounts’ email messages directly from your {product-abbrev}
account. When you set up to access other external mail accounts, you can
specify where the messages are saved and create a persona to be used when
you reply to or forward a message received from that external account.

Messages from your external account are not automatically received in your
{product-abbrev} account. Click the *Refresh* icon on the toolbar to get
the latest messages.

If you set up add an external POP account, you can configure the POP access
behavior when messages are downloaded to your account.

=== Add External Accounts

  . Go to the *Preferences>Accounts* page.

  . Click *Add External Account*. The account name *New External Account*
    displays in the Account Name column and in the *External Account
    Settings>Account Name* text box. You can change this.

  . In the *External Account Settings* section, enter the email address of
    the external account.

  . In *Account Name* text box, enter a descriptive word to identify this
    account. This is used to identify the external account.

  . Select the type of account: *POP* or *IMAP*.

  . In the *Username of Account* text box, enter the name associated with
    this email account. Sometimes your user name is the part of your email
    address before the @ and other times it is your full email address.

  . In the *Email Server* text box, enter the name for your external
    account’s server.

  . In the *Password* text box, enter the password you use to sign in to
    this external account. To see that the password you typed is correct,
    select *Show password*.

  . If your service provider uses a different port than the default, change
    it in the *Advanced Settings* area. If you use a secure connection,
    enable *Use an encrypted connection (SSL) when accessing this server*.

  . Your provider should let you know if they do not use a standard IMAP
    (143) or POP (110) port.

  . Click *Test Settings*. The information is verified.

  . Select the folder the messages should be downloaded to.

  . To delete messages from the external account after you receive them in
    your account, check *Delete messages on the server after downloading
    them*.

  . Configure the From name, reply to address and signatures settings for
    messages you send.

    * Type the name that should appear in the *From* field of your outgoing
      email messages (for example, John). This is the name that is shown
      before your email address.

    * To direct replies to email messages from this persona to a name and
      address different from that which you configured in *From*, select
      *Set the “Reply-to”* field of email messages to.  Enter the name in
      the text box.

  . To associate a signature with the persona, select *Signature:
    <<_using_signatures_automatically,Manage your signatures...>>*

  . Click *Save*.

See <<_set_up_pop_behavior_for_your_account>>

== Receiving New Mail Notification to Another Email Address

You can configure your email preferences to notify you at another email
address when you receive an email message to your mailbox. This feature
might be useful if you do not receive a lot of email to this account, but
when you do receive email, it's important enough to require a timely
response.

  . Go to the *Preferences>Mail* page.

  . In the *Receiving Messages>Message Arrival* section, select *Send a
    notification message to*.

  . Enter the email address in the text box.

  . Click *Save*.

== Set Up POP Behavior for Your Account

If you set up add an external POP account, you can configure the POP access
behavior when messages are downloaded to your account.

  . Go to the Preferences>Mail page, Access from Other Mail Clients section.

  . Select how messages received from your POP accounts should be handled.
+
[cols="1,2a",options="header",]
|=======================================================================
|Option |Description

|Message Downloads |

Select whether all mail saved in your POP account should be downloaded to
your account or only new mail received beginning when you set up the access
to the external account.

|Incoming Junk Messages |

Select this if you want messages sent to your POP account Junk folder sent
to your account. The messages are added to your POP account folder.

|Incoming Deleted Messages |

Select how you want messages you deleted in your POP account to be saved to
your account.

|=======================================================================

  . Click *Save*.
