= Sending Secure Email Messages (Network Edition Only)

== Setting up S/MIME to send and receive signed and encrypted email messages

include::networkadvancedonly.adoc[]

If the S/MIME feature is enabled for your account, you can send and receive
digitally signed and encrypted messages.

To use S/MIME with the {product-name} you must have a secure email signing
certificate suitable for S/MIME signing and encryption. The certificate
with private key must be installed in the local certificate store on
Windows computer, Mac OSX computer, or in the browser certificate store if
using Firefox. For information about how to install your certificate see
the appropriate computer or browser documentation.

To send and receive encrypted and signed messages your public key and
recipient's public key must be exchanged. To get a copy of a recipient's
public key, you can send a digitally signed message using your certificate
to the recipient and request that they send you a digitally signed message
in reply. When the message is received, the recipient's certificate is
stored in the recipient's contact page in Address Book, or a contact is
automatically created.

Note the following differences when working with encrypted messages:

  * If you are sharing your Inbox, delegated users cannot read your
    encrypted messages from their computers. Your private key is required
    to read encrypted messages.

  * You cannot run spell check on encrypted messages.

  * You cannot search for text in the body or attachments of an encrypted
    message.  Only the header information such as sent to or from, date
    message was sent, or subject can be found in a search.

== Setting Security Preferences for using S/MIME

include::networkadvancedonly.adoc[]

If the S/MIME feature is enabled for your account, a Security page is
available in your Preferences.

The default setting for the Security preference is to automatically
remember the last security option you selected when you composed an email.

You can change the default preference to always send your messages as
signed, as signed and encrypted, or to not sign or encrypt your messages.
You can change the option from the Security tab in the compose page, but
the change is only for that message.

  . Click *Preferences*.

  . In the Overview pane, click *Security*.

  . Change the settings.

    * *Auto (remember last settings)* is the default. The last security
      option you select is remembered

    * Select *Do not sign or encrypt* if you do not use the S/MIME feature
      at all or rarely

    * Select *Sign only* if you always send your email with a digital
      signature

    * Select *Sign and encrypt* if you always send your email encrypted
      with a digital signature

  . Click *Save*.

== Adding Certificates to Contacts

include::networkadvancedonly.adoc[]

The contact page in the Contacts includes a Certificate field. When a
message with a certificate is received from someone listed in your address
books, the certificate is stored in the recipients contact page in the
address book.

If a signed message is received from a recipient who is not an existing
contact in your address book, a new contact is automatically created in the
Emailed Contacts address book and the certificate is stored with the newly
generated contact.

You can also upload the recipient’s certificate if it is sent as an
attachment.

== Compose and Send a Digitally Signed Message

include::networkadvancedonly.adoc[]

Digitally signed messages can be sent to recipients that have sent you
their certificate. The recipient’s certificate is stored in the recipients
contact page in Contacts.

  . From the Mail tab, click *New Message* from the toolbar.

  . In *To:* enter the user's address or click the To: link to search for
    an address from you address books.

  . If your security preference is not set by default to send digitally
    signed messages, click *Security* and select *Sign only*.

  . Enter a subject of the message.

  . Compose the message.

  . To add an attachment, click *Add Attachment* and browse to the file, or
    drag and drop the file from your computer to the email header.

  . Click *Send*.

== Compose and Send an Encrypted Message

include::networkadvancedonly.adoc[]

Messages can be sent encrypted to recipients that have sent you their
public key and certificate. The recipient’s certificate is stored in the
recipients contact page in Address Book.

  . Click *New Message* on the toolbar.

  . If you security preference is not set by default to send encrypted and
    digitally signed messages *Click Security* and select *Sign and
    Encrypt*.

  . In *To:* enter the user's address or click the To: link to search for
    an address from you address books.

  . Enter a subject of the message.

  . Compose the message.

  . To add an attachment, click *Add Attachment* and browse to the file, or
    drag and drop the file from your computer to the email header section.

  . Click *Send*.

    * You cannot save a draft of a message encrypted.

    * You cannot run spell check on encrypted messages.
