= Voice Service (Network Edition Only)

== Listening to a Voice Mail Message

include::networkadvancedonly.adoc[]

When you receive a voice mail message, you receive a message in your Inbox
with an attached message in a voice format, such as .wav.

Message details are included in the message, such as the phone number the
message is from, the duration of the call, and the date and time the call
was received. You can play the voice message recording by clicking the
voice mail message attachment, or you can go to the Voice tab and click the
play arrow to play the message.

Because this voice mail is received like any other email message, you can
reply or forward the message, or perform other actions that are typical
with an email message such as tagging the message. You can download the
message to a folder, place the message in briefcase, or remove the message.

=== Play a Voice Mail Message from the Voice Mail Page

  . Select the Voice tab.

  . In the call history, select the voice mail message you want to play.

=== Play a Voice Mail Message from an Inbox Message

  . Select an email message in your Inbox that has a voice mail message
    attachment.

  . Click the *Voice Message* attachment to play the message.

=== Marking a Message as Heard or Unheard

. Select the Voice tab.

. In the call history list, right click a voice mail message.

. Click *Mark as Unheard* or *Mark as Heard*, depending on how you want to
  show the message in your Inbox.

== Making a New Call with the Voice Service

include::networkadvancedonly.adoc[]

You can make calls from all registered phone devices, including soft phone
clients such as Cisco or Mitel.

  . On the Voice page, click *New Call*. A new call dialog box displays.

  . Select the *From* number from the drop down menu. The numbers listed
    are those that are registered to you.

  . Enter or select the *To* number for which you want to make the
    call. The number can be obtained from your address books or contact
    cards, or you can enter a number manually.

  . Click *OK* to make the call. Use the phone device associated with the
    phone number you are using to make the call

=== Ending a Call

To end a call, hang up the phone or click in the dialog box to hang up.

== Calling Back a Voice Mail Message

include::networkadvancedonly.adoc[]

Reply to a voice mail message by calling the sender back using the
Click-To-Call feature.

  . Select the Voice tab.

  . In the call history list, select the voice mail message you want to
    reply to.

  . Click *Call Back*. The number that is associated with the caller is
    dialed.

== Using Presence to Make Your Status Known

include::networkadvancedonly.adoc[]

[NOTE]
Cisco clients only

Rich Presence information is displayed about you or a contact using the
Cisco Jabber Client.

Presence status is displayed as available, away, on a call, or do not
disturb. To see the presence status, hover over a contact card and the
presence status of the contact displays. For example if you are on the
phone, your presence status displays that you are on a call. You can also
change your status manually from the presence drop-down menu.

== Click to Call in Voice Service

include::networkadvancedonly.adoc[]

[NOTE]
Cisco clients only

Use the Click-to-Call feature to click a phone number to call a contact.

Open a contact, and based on the presence status of the contact, click the
phone number link on the contact card to call the recipient.

== Adding Caller Information to Your Contacts

include::networkadvancedonly.adoc[]

  . Select the Voice tab.

  . In the call history, right click a voice mail message.

  . Select *Add to Contacts* and complete the new contact form.
