= Composing Email Messages

== Composing and Sending Email

You can compose and send your email messages as soon as you write them;
compose a draft and return to it later to finish and send, or compose the
message and specify a time in the future to send the message.

You can customize your options for composing messages in your
*Preferences>Mail* page.

=== Composing a new email message

Depending on your mail preferences, when you click *New Message* either a
Compose tab appears in the Application toolbar or the compose page opens in
a separate window.

  . In the Mail tab click *New Message*.

  . In the *To* text box, enter the email addresses of the person or persons to
    whom you are sending the message. Either type the address or click *To* to
    search through your contacts or the global address list.
+
[NOTE]
You can drag and drop the address bubble in the text box to the Cc or Bcc
text boxes, and you can copy the address bubble by clicking CTRL+c.  The Bcc
field is available from the Options dropdown menu.

  . If you have more than one email identity (also known as a persona)
    configured, *From* is displayed above the *To*: field. Select the identity
    to use for this email.

  . (Optional) In *Options*, click *Signature* and select the signature that
    should be added to the message.

  . (Optional) To send a copy of the email to other recipients (Cc) or to send a
    blind copy (Bcc) without the recipient's knowledge, enter email addresses in
    the Cc and Bcc fields.
+
[NOTE]
You can send a message without an address in the To field if there is an
address in either the Cc or Bcc field.

  . In the *Subject* field, tell the recipient what the message is about.

  . Click *Send* to send the email message.

A copy of the message you sent is saved in your Sent folder.

If you don't want to send the message immediately, instead of clicking Send,
click the arrow next to Send and select Send Later. In the Specify Message
Send Time dialog enter the date and time to send the message. The message is
saved in the Draft folder and is automatically sent on that date and time.

See also:

<<_customizing_your_options_for_composing_messages>>

<<_using_html_to_compose_messages>>

== Customizing Your Options for Composing Messages

From your preferences you can select to create simple plain text messages or
create messages with HTML styling, and you can set up signatures and
personas that can be applied to messages you send.

In addition to the options for composing messages, other options you can set
up include return receipt requests, whether to compose messages in a new
window and to require that your messages are spell checked before they are
sent.

  . Go to the *Preferences>Mail* page, *Composing Messages* section.

  . Select how you want your messages to be sent, *As HTML* or *As Text*.

  . If you select *As HTML*, in the drop down menus, select the *Font* style,
    *Size*, and *Color*.

  . In *Settings*, select the options for how you want to manage composing
    messages.
+
[cols="1,2a", options="header"]
|=======================================================================
|Option |Description

|Automatically save drafts of messages while you are composing |

While you compose your message, a copy is periodically saved in your Draft
folder.

|Always request read receipt |

All messages you send request a return receipt message sent back to you
when the recipient opens your message.

When you set this as your default, you can change this for individual email
messages from the *Options* drop-down menu on the compose toolbar.

|Reply/Forward using for­mat of the original message |

Even if your default text editor is different from the message received,
check this box to reply to the message in the same format as received.
This is useful to make sure the recipient can get the message in the best
format they can read.

|Always compose in new window |

A separate compose window opens. You can view and navigate within your
mailbox while the compose window is open.

|Mandatory spellcheck before sending a message |

All messages are automatically spell checked before they are sent.

|Save a copy to Sent folder |

This is enabled by default. You can deselect this option.

|Use keyboard shortcut Ctrl+Enter to send message |

You can select to use the keyboard shortcut Ctrl+Enter to send a
message. If you enable this option, be aware when using this keyboard
shortcut to complete your message before using.

|=======================================================================

  . (Optional) For additional composing options, click the link to the *Accounts
    Page* or go to the *Preferences>Accounts* page and set up your personas.

  . (Optional) To manage your signatures, go to the *Preferences>Signatures*
    page and add signatures that can be used when sending messages.

  . Click *Save*.

== Addressing a Message

The auto complete feature suggests names as you type into the *To*, *Cc*,
and *Bcc* fields in a new message. A list of possible addresses from your
contacts in which either the first name, last name, or email address starts
with the text you typed is displayed.

As you continue to type, the list of matching addresses becomes smaller as
fewer matches are available. The list disappears if there are no matches.

For example, to send an email message to David Brinks, whose email address
is dbrinks@acme.com, when you type D, a list appears showing all possible
matches, with the matching portions highlighted. In this case, it might
display:

  * Dale Edwards <ded@acme.com>
  * David Brinks <dbrinks@acme.com>
  * Erica Dodd <erica878@xyz.com>

When you add an “a” (Da) into the To field, the list would display:

  * Dale Edwards <ded@acme.com>
  * David Brinks <dbrinks@acme.com>

=== Use Automatic Address Completion

To select a match from the list, you can click the match with the mouse or
use one of the following keys to perform an action:

  * The comma, semicolon, Return/Enter, and Tab keys all complete the first
    match in the list and place it in the field.

  * ESC hides the list.

  * The up and down arrow keys change the selection in the list. Moving the
    mouse cursor over the list also changes the selection.

To select an address when composing an email

  . Type enough characters until the contact you want is the first match.

  . Press a quick key, such as Enter or the semicolon. The address displays
  in the recipient field.

== Using Signatures Automatically

You can include an automatic signature at the end of an email. A signature
can include your name and any additional text. If you are using an HTML
editor, you can format your signature, add a link to a URL and add graphics.

You can create more than one signature. For example, you can have a formal
signature for emails sent to customers and an informal signature for emails
sent to friends.

If you create multiple email identities (also known as personas), you can
create different signatures and assign them to specific addresses.

  . Go to the *Preferences>Signatures* page.

  . In the *Name* text box, type a descriptive name to identify the
    signature. You can create multiple signatures, so using an identifiable name
    here is helpful.

  . (Optional) To format in plain text, click *Format As HTML* dropdown menu and
    select *Format As Plain Text*.

  . In the text box, type the signature text as you want it to appear. If you
    are using *Format as HTML*, you can add images and create links to your
    signature text.

  . In the *Using Signatures* section, select the default signature, or primary
    account signature, from the drop down menu to use with messages sent from
    your various accounts.

  . Select the placement of your signature in a message.

    * Select *Above included messages* to add your signature at the end of your
      reply and before the included messages.

    * Select *Below included messages* to add your signature at the end of the
      message.

  . Click *Save*.

== Using Other Account Identities When You Send an Email

When you send email, it is identified with an email account. When your email
account is set up, your account name is your primary identity. However, you
can create other email identities called personas to manage different types
of email.

For example, you can create one persona for your business email and another
for your personal email.

If you have more than one persona or added external accounts, when you send
an email you can select the account you want to use as the From address.

See <<_add_personas>>

== Add Personas

Creating different personas allows you to use multiple email addresses from
your mailbox. For example, you could use your primary account persona for
your business email correspondence, and create a new persona for your
personal email correspondence.

  . Go to the *Preferences>Accounts* page. Your default account and personal
    information is shown as the primary account.

  . Click *Add Persona*. The account name *New Persona* displays in the Account
    Name column and in the *Persona Settings>Persona Name* text box.

  . In the *Persona Name* text box enter a descriptive word to identify the
    persona in the From list when you are composing an email. This name does not
    appear in the email message.

  . In the *Settings for Sent Messages* section, specify the From information
    for this persona.
+
In the *From* text box type the name that appears in the From field of your
outgoing email messages. This is the name that is shown before your email
address.
+
In the drop-down menu next to the text box, select the email address from
which to send messages. If this field is not editable, you do not have
additional external accounts identified.

  . To direct replies to email messages from this persona to a name and address
    different from that which you configured in From, check *Reply-to>Set the
    "Reply-to" field of email messages to*, and enter the name to use in the
    text box.

  . (Optional) To associate a signature with the persona, click *Signature:
    Manage your signatures...*

  . To automatically *Use this persona* when replying to messages sent to a
    specific email address or when forwarding messages from that address, select
    *When replying or forwarding messages sent to*, and type the email address
    in the text box. If you are entering more than one email address, separate
    the addresses with either a comma or a semi-colon.

  . To automatically *Use this persona* when replying to messages in a specific
    folder or when forwarding messages from this folder, select *When composing,
    replying to or forwarding messages in folder(s)*. Click the folder icon to
    select one or more folders or to create a new folder.
+
If you are selecting more than one folder, separate the folder names with
either a comma or a semi-colon.

  . Click *Save*.

== Mark the Priority Level of a Message

You can indicate a message’s level of importance. For example, if you have a
request that needs to be replied to as soon as possible.

  * Before you send the message, in the *Options* drop-down menu in the message
    header, select the priority option, *High priority*, *Normal priority*, or
    *Low priority*.

The recipient sees the message priority flag in their mailbox and in the
message.

== Request a Return Receipt

Message you send to other {product-abbrev} users can be marked to request a
return receipt when the recipient opens your message. However, the
recipients must have the Return Receipt feature enabled for their accounts.

=== To set this as the default

  * Go to the *Preferences>Mail* page, and in the *Composing Messages* section,
    select *Always Request read receipt*.

=== To set this request per message

  * When composing a message and before sending the message, in the *Options*
    drop-down list, select *Request Read Receipt*.

== Adding Attachments

You can attach any file on your file system that you can find using Browse.

You can open any file attachment directly from your mailbox, provided that
you have the right application and the extension is not blocked by your
administrator.

If the file type is one that is supported by the installed software on your
computer, you can typically double-click the file and your computer
automatically launches the right application for reading that file.

Computer viruses are often spread through file attachments. Therefore,
system administrators might block incoming email containing certain types of
attachments, often with the extension .EXE or .ZIP as part of their
filename. If you send an email message to someone whose email system has
been configured to block certain types of attachments, you might not receive
any notification if the email was blocked.

=== Add an Attachment to a Message

You can attach documents, spreadsheets, pictures, slide shows, and other
types of files to an email message.

  . Compose the email message.

  . Below the *Subject* field, click *Attach* and select *My Computer*.

  . Select the files and click *Open*. The file names displays below the Subject
    text box.

  . Click *Send* to send the message and the attachments.
+
[NOTE]
Recipients must have the appropriate software to open the file. Common file
formats, such as text files, HTML files, and images such as GIF or JPEG
files, can be opened in a variety of programs.

=== Add Attachments Using Drag and Drop

You can easily add an attachment to an email message by dragging the file
from a folder into your email.

  . Select one or more files and hold down the cursor on the file(s) to be
    attached.

  . Drag the files to the message header area and release the cursor. The file
    names are displayed in the header.

=== Removing an Attachment

To remove an attachment, click the *x* in the attachment bubble.

== Spell Check a Message

You can use the spell check feature at any time to check your spelling.

  . On the toolbar, click the *Abc* link. Words in the email message that are
    unknown to the spell checker are highlighted.

  . Right-click on a highlighted word. A drop-down menu displays suggested
    corrections.

  . Select the correct word. The word is highlighted in another color.

  . To accept your changes and close the spell checker, click *Resume editing*.

Before you close the spell checker, you can change a corrected word back to
the original spelling. Click on the highlighted word and select the initial
spelling from the top of the pop-up.

=== Spell Check All Messages Before They are Sent

  . Go to *Preferences>Mail>Composing Messages>Settings*.

  . Select the option *Mandatory spellcheck before sending a message*.

  . Click *Save*.

== Adding Words to the Spell Dictionary

  * Right-click on the correctly spelled word and click *Add to Dictionary*.

You cannot remove words from your dictionary after they are added. You can
also configure the spell check to ignore words, right-click on the word and
click Ignore.

== Save a Message as a Draft

You can save a message to finish and send later.

  * Click *Save Draft*. The message is saved in the Drafts folder.

To retrieve a draft, open the Drafts folder and click on the message. To
continue editing the draft message, click Edit. When the message is sent,
the message is removed from the Drafts folder.

== Sending email on behalf of someone else

If you have been granted delegate permissions for another person, you can
send <<_delegate_others_to_send_messages_on_your_behalf,email messages on
their behalf>>. The message's From address includes both your email address
and the person you are sending the message for. If you were given permission
to send a message as that person, the person's email address is in the
menu.  When you select this, your address is not included in the message.

  . In your Inbox, click *New Message*.

  . In the *From* field, select the name of the sender from the drop-down menu.

  . Compose and send the message.

== Deleting a Message

You can delete specific email messages or a complete conversation thread.

  * Right-click the message or conversation to delete and select Delete.
+
Deleted messages are moved to your Trash folder.
+
You can recover files from Trash within 30 days of deleting them. After 30
days, the items are permanently deleted.

  * To permanently delete a message, click Shift>Delete.
+
Messages are permanently deleted from your account.
