= Getting Started with the {product-name}

== Advanced Web Client
The {product-name} ({product-abbrev}) is a full-featured messaging and
collaboration application that offers reliable, high-performance email,
address books, calendaring, task lists and document authoring capabilities.

[NOTE]
Your account might not include all the features described in this
Help. Check with your system administrator to see which features are enabled
for your account.

The basic applications you can use in your {product-name} account include:

  * Email

  ** <<_composing_email_messages,Compose and send new messages>>

  ** <<_adding_attachments,Add attachments to your messages>>

  ** <<_using_signatures_automatically,Add signatures to your messages>>

  ** <<_managing_your_email,Track mail exchanges using the Conversation feature>>

  ** <<_organizing_your_account,Create your own folders and tags to organize mail>>

  ** <<_working_with_email_filters,Create filters to route your email messages to designated folders>>

  * Address Book

  ** <<_using_address_books,Create and manage multiple_address_books>>

  ** <<_importing_an_address_book,Import>> and <<_exporting_an_address_book,export>> contact lists

  * Calendar

  ** <<_create_a_calendar,Create and manage multiple calendars>>

  ** <<_working_with_calendars,Set up how your calendar looks>>

  ** <<_scheduling_appointments_meetings_and_events,Create appointments, meetings and events>>

  ** <<_import_your_ical_calendar,Import>> and <<_export_your_ical_calendar,export> other calendar programs

  * Tasks

  ** <<_creating_a_task_list,Create task lists>>

  ** <<_creating_a_task,Create to-do tasks>>

  ** <<_create_a_detailed_task,Manage a task, set the priority and track the progress>>

  * Preferences

  ** <<_customizing_your_mailbox_initial_view,Customize your mailbox view>>

  ** <<_personalizing_the_view_of_your_account,Configure your account settings>>

  ** <<_using_keyboard_shortcuts,View shortcut key combinations available for quick navigation withing your mailbox>>

In addition, you can search for email messages, contacts, calendar events
and task lists from any view. See <<_navigating_the_zimbra_web_client>>.

== Using Advanced and Standard Clients

Two versions of the {product-name} are available.

  * *Advanced Web Client* version offers the full set of Web collaboration
    features. It works with most current browsers and faster Internet
    connections.

  * *Standard Web Client* version. If you have a slow Internet connection or
    prefer HTML-based messaging, you can use the Standard Web Client which
    has many of the same features as the Advanced Web Client version but
    might be accessed differently.

=== Browser Tools

  * The browser's *Back* button takes you to the previous page you were
    viewing. You can also use the *Forward* button.

  * Do not use the browser's *Reload* (Refresh) button. Doing so will restart
    your session.

=== Switch Client Versions

You can set the default client version to sign in to. If you are frequently
changing which client you are using, you can change it.

  . Go to the *Preferences>General* page.

  . In the Sign in section, select how you want to sign in.

  .. *Advanced*. Offers the full set of Web collaboration features. This Web
     Client works best with newer browsers and faster Internet connections.

  .. *Standard*. Recommended when Internet connections are slow, when using
     older browsers, or for easier accessibility.

  . Click *Save*.

The next time you sign in, your selection appears as the default.

== Signing In and Signing Out

You must use a browser to run the {product-abbrev}. Not all browsers are
supported, so check with your administrator.

When you sign in to your account, you enter your name and password, and
select the client version to use. You can select to use the *Default*
client, or change the client version.

Your session remains active until the session expires. If you select the
*Stay signed in* option, you do not have to sign in every time you restart
the browser during a day.

If you leave your web client open but do not access your mailbox for a
period of time, your session might time out and you will need to sign back
in.

=== Sign In

  . Open a browser window and enter the URL provided by your administrator.  For
    example: *https://mail.domain.com/zimbra/mail*

  . When the sign in screen appears, type your *Username*. You might be required
    to type your full email address as the username (for example,
    myra@example.com) and your *Password*.

  . To be remembered on this computer until the session expires or you sign out,
    check *Stay signed in*.

  . If you do not want to use the *Default* client, you can change the version.

  . Click *Sign In*.

=== Sign Out

To prevent others from having access to your email account, you should
always sign out when you are not using your computer. If you browse to a
different site without signing out first, your session might sign out
automatically when it reaches the specified timeout.

  * In the drop-down menu arrow next to your name in the top right corner,
    select *Sign Out*.

== Changing Your Password

You can change your password. If you have trouble changing your password or
have forgotten your password, or if the *Password* option is not displayed,
contact your administrator.

  . Go to the *Preferences>General* page.

  . In the *Sign in>Password* section, click *Change Password*.

  . Enter your *Old password*, *New password*, and *Confirm*.

  . Click *Change password*.

  . Click *Save*.

== Using Keyboard Shortcuts

Many of the functions and commands have keyboard shortcuts.

=== View Shortcut Keys

  * To view a list of shortcuts while working in your mailbox, press *Ctrl+q*.

  * If you want to leave the shortcut window open while you work in your
    account, click *New Window*.

=== Print Shortcut Keys

  . Go to the *Preferences>Shortcuts* page for a list of shortcut keys.
  . Click *Print* in the upper right to print the list.
