= Reading Messages

== Reading Mail

By default new messages are placed in your Inbox. If you have mail filter
rules, new messages can appear in folders other than your Inbox. The number
in parentheses next to each folder name indicates the number of unread
messages within that folder.

=== Read a Message in Conversation View

  . To read a message in the Conversation view double-click the conversation
    containing the message. The Content pane changes to show the individual
    messages in the conversation.

    * To expand the message to see all the conversations, click *Show quoted text*
      at the end of the message.

    * To collapse the conversation view so only the last message is displayed,
      click *Hide quoted text* at the end of the message.

    * To collapse all messages to view only the sender’s name and the snippet of
      the first line of the message, double-click in the message header.

  . To open the message, click the line that contains the message you want to
    read.

If you have Reading Pane enabled, the message body appears in the Reading
Pane. Otherwise, double-click the message. The message is displayed in the
Content pane.

=== Read a Message in Single Message View

  * If the Reading Pane feature is enabled, click the message and read it in the
    Reading Pane.

  * If the Reading Pane feature is not enabled, double-click the message. The
    message is displayed in the Content pane.

== Using a Reading Pane

You can use the Reading Pane to preview messages in your Inbox and other
folders. If you have the Reading Pane on, when you click on an email
message, the message displays in the Reading Pane and the message is marked
as read.

To adjust the size of the Reading Pane, place your pointer on the divider
bar and drag the bar.

=== Turn Reading Pane On or Off

The Reading Pane lets you read email messages from your Inbox without
opening the email. Depending on your view, the Reading Pane can be at the
bottom or on the right, or turned off.

  . On the *Mail* tab toolbar, click the *View* drop-down menu.

  . Select the Reading Pane option.

=== Set the Reading Pane for Marked as Read Behavior

You can also select whether messages you view in the Reading Pane are marked
as read or not marked as read.

  . Go to the *Preferences>Mail* page.

  . In the *Displaying Messages>Reading Pane* section, select how messages are
    handled when the message is selected.

  . Click *Save*.

== Displaying Messages in HTML Format or Plain Text

You can view email messages in two formats, HTML or plain text.

  * HTML messages can have text formatting, numbering, bullets, colored
    background, and links, which can make messages easier to read.

  * Plain text messages can always be read by other email clients. Plain text
    does not support any text formatting, styles, links or images. You can view
    a message in plain-text mode even if it contains HTML. The HTML tags are
    displayed in the body of the message in the plain text view.

=== Set Message Display Format

  . Go to the *Preferences>Mail* page.

  . In the *Displaying Messages>Display Mail*, select either *As HTML (when
    possible)* or *As Text*.

  . Click *Save*.

== Returning Read Receipts

Messages you receive from other ZWC users can be marked to request a return
receipt message to be sent back when you open your message. You can specify
how to handle return receipt requests:

  . Go to the *Preferences>Mail* page, *Receiving Messages* section

  . In the *Read Receipt* section, select how you want read receipt requests to
    be handled.
+
[cols="1,2a", options="header"]
|=======================================================================
|Option |Description

|Never send a read receipt |

When a message is received with a return read receipt request, the request
is ignored. You are not informed of the request. This is the default.

|Always send a read receipt message |

A return read receipt message is sent when you open an email flagged for a
return receipt.

|Ask me |

You are given the option to send a receipt when you open an email flagged
for a return receipt.

|=======================================================================

  . Click *Save*.

== Print a conversation (all messages)

Right-click the conversation to be printed, and select Print. The
conversation opens in a new window. A standard print dialog appears.

  . Select a printer.

  . Click *OK*. The conversation is sent to the selected printer.

  . Close the conversation window.

  . Alternately, you can select Print from the Actions dropdown menu on the
    toolbar.

=== Print one message in a conversation

  . Open the conversation and select the message to print.

  . At the end of the message, click the *More Actions* and select *Print*. The
    message opens in a new window. A standard print dialog appears.

  . Select a printer.

  . Click *OK*. The message is sent to the selected printer.

  . Close the message window.

== Printing an Email Message

The default font size used when a message is printed is 12 points. You can
change this from the *Preferences tab>General* page.

[NOTE]
Do not use the browser's *File>Print* feature. The page will not be
well-formatted, and your message may be difficult to read.

  . Right-click on the message and select *Print*. The message opens in a new
    window. A standard print dialog appears.

  . Select a printer.

  . Click *OK*. The message is sent to the selected printer.

  . Close the message window.

Alternately, you can select *Print* from the Actions dropdown menu on the
toolbar.

== Receiving a “Permission Denied” Message

If you send out an invitation to a meeting and you receive an email message
that says “You do not have permission to invite this users to a meeting”
from an attendee, the attendee has set up their Calendar permissions
preferences to limit who can invite them to a meetings.

== Opening Attachments to an Email Message

Email messages can include attached files such as word processing documents,
spreadsheets, text files, ZIP files, images, executable applications, or any
other type of computer file that resides on the sender's computer
network. Messages that contain attachments display a paper clip next to the
subject.

You can open any file attachment directly from your account, provided that
you have the right application and the extension is not blocked by your
system administrator.

If the file type is one that is supported by the installed software on your
computer, you can typically double-click the file and your computer
automatically launches the right application for reading that file.

Computer viruses are often spread via file attachments. Therefore, system
administrators might block incoming email containing certain types of
attachments, often with the extension .EXE or .ZIP as part of their
filename.

Computer viruses can spread through email attachments. It is considered
standard practice for system administrators to implement virus filtering for
incoming mail as well as virus scanning for personal computers. However,
there is always a chance that something could get through.

In the case of email viruses, the majority of them are activated when a file
attachment containing the virus is opened or viewed. Many of these viruses
have been known to spread themselves using entries in users' address
books. Therefore, we recommend that you use care when opening file
attachments, even from senders who appear to be known to you.

=== View Attachments

To view an attachment open the message:

  * Click the name of the attachment to open the attachment (if you have the
    correct application available).

  * Click *Download* to select whether to open the file or save it on your
    computer. If you select *Save to Disk*, a browser dialog box appears so that
    you can select where to save the file.

The file is still attached to the message until you remove it.

=== Preview Attachments

If you have the Preview option, you can quickly view the content of the
attachment without having to download or open the attachment.

  * To preview an attachment, open the message and click *Preview* next to the
    attachment. This opens the attachment even if the application is not
    installed on your network.

=== Remove Attachments

Attachments to your email affect your quota. You may want to remove larger
attachments from the message. Removing the attachment deletes the file from
your mailbox. If you downloaded the file, you still have a copy.

  * To remove an attachment open the message and click *Remove*.
