= Scheduling Appointments, Meetings and Events

== Scheduling Appointments, Meetings, and Events

You can create single or recurring appointments, meetings and events. While
creating an appointment you can see if attendees are free before inviting
them, reserve a room and equipment and write a message that is sent with the
invite.

Activities you schedule include:

  * *Appointments*. An appointment is an activity that you schedule that
    does not include other people or resources. When you schedule an
    appointment, no email is sent to confirm the appointment. You can set
    recurring appointments. *QuickAdd* can be used to quickly create an
    appointment.

  * *Events*. An event is an activity that lasts all day. Events do not
    display as time on the calendar, they appear as banner at the top of
    the calendar schedule.

  * *Meetings*. Meetings are appointments that include other people. When
    you create a meeting, you select attendees and resources and send an
    email invitation to them. You can reschedule meetings and set up
    recurring meetings.

== Creating an Appointment Quickly

The QuickAdd option makes it easy to quickly create an appointment for
yourself.

[NOTE]
The QuickAdd feature is an option. If you would prefer to always open the
Appointment page when you double-click or drag on the calendar, disable this
feature from your Calendar Preferences.

  . Right-click on either the mini-calendar or the start time in one of your
    calendar views. You can select to create a *New Appointment* or a *New All
    Day Appointment*.

  . In the *Subject* text box, add a brief description of the meeting. The text
    added here becomes the description in the calendar.

  . In the *Location* text box enter where the meeting is. If the location is in
    the company directory, when you start to type, locations that match are
    listed. You can also click *Suggest a location* to see a list of available
    locations in your company

  . In the *Display* drop down menu, select the Free/Busy option for this
    appointment.

  . If this appointment should be added to a calendar other than the default
    Calendar, select the calendar.

  . In the *Mark As* drop down select where the appointment is private or
    public. Details about events that are marked private do not display in a
    grantee's shared calendar. Only the start and end time, duration, recurrence
    information, and the organizer's identity are shown in the shared calendar.

  . Define the start and end day and time. If the appointment is recurring, in
    *Repeat*, select the how often this appointment should be scheduled.

  . (Optional) If you want to add other attendees, schedule a resource, or add
    notes to the appointment, click *More Details*.

  . Click *OK*.

== Creating a Meeting from the Appointment Page

You can create an appointment from the Calendar tab.

  . On the Calendar header, click *New Appointment*.

  . If the *From* field displays above the Subject line, you created more than
    one persona for your account. Select the identity to use when creating this
    appointment.

  . In the *Subject* text box, add a brief description of the meeting. The text
    added here becomes the description in the calendar.

  . Define the start and end day and time. If the appointment is recurring, in
    *Repeat*, select the how often this appointment should be scheduled. Select
    *All day* to make this appointment all day.

  . In the *Attendees* text box, type the email addresses, separating addresses
    by a semicolon (;). As you enter names, the Scheduler opens and the
    attendees' free/busy information is displayed.
+
To help you find a time when all attendees are available, click *Suggest a
time*. A calendar displays with the availability. As you enter attendee
names, the scheduling tool begins to suggest times that all the attendees
are available.
+
[NOTE]
If an attendee has set a preference to allow only certain users to see
free/busy information and you are excluded from the list, you cannot view
the free/busy schedule
+
If some attendees are not required to be at the meeting, but you want to
invite them, select *Show Optional* and type email address in the field. You
can also do this in the Scheduler. Click the icon next to the name and
select *Optional Attendee*. When the invite is sent, their names are listed
as optional.

  . In the *Location* text box enter where the meeting is. If the location is in
    the company directory, when you start to type, locations that match are
    listed. You can also click *Suggest a location* to see a list of available
    locations in your company.

  . Click *Show Equipment* if you want to reserve equipment resources that have
    been identified in your company’s directory.

  . In the *Display*, select the Free/Busy option for this appointment, which
    calendar the appointment should be added to, and whether this appointment
    should be marked as Private.

  . In the *Reminder* drop-down menu, set an alarm notification to remind of the
    appointment.

  . To receive a notification of this meeting, check the appropriate box,
    *Email* or *SMS*.  If you have not configured a notification method, click
    *Configure* to go to the
    *<<_setting_email_and_sms_reminder_notification,Preference>Notifications>>*
    page to set this up.

  . In the text box below Scheduler, type an email message that is included in
    the appointment invitation. To add attachments, click the paperclip icon on
    the toolbar.

  . The default is to ask the attendees to reply to your invitation. If you do
    not want a response from the attendees, in the Calendar toolbar, click
    *Options>Request* Response to remove the check mark.

  . If you do not want to send the invite out at this time, click
    *Save*. Otherwise click *Send*.

== Scheduling an All-Day Appointment

You can use the calendar to schedule an all day appointment, which is called
an event.

  . On the Calendar header, click *New Appointment*.

  . If the *From* field displays above the Subject line, you created more than
    one persona for your account. Select the identity to use when creating this
    appointment.

  . In the *Subject* text box, add a brief description of the meeting. The text
    added here becomes the description in the calendar.

  . Select *All day* and select the start and stop date.

  . In the Attendees text box, type the email addresses, separating addresses by
    a semicolon (;). As you enter names, the Scheduler opens and the attendees
    free/busy information is displayed.
+
To help you find a time when all attendees are available, click *Suggest a
time*. A calendar displays with the availability. As you enter attendee
names, the scheduling tool begins to suggest times that all the attendees
are available.
+
[NOTE]
If an attendee has set a preference to allow only certain users to see
free/busy information and you are excluded from the list, you cannot view
the free/busy schedule
+
If some attendees are not required to be at the meeting, but you want to
invite them, select *Show Optional* and type email address in the field. You
can also do this in the Scheduler. Click the icon next to the name and
select Optional Attendee. When the invite is sent, their names are listed as
optional.

  . In the *Location* text box enter where the meeting is. If the location is in
    the company directory, when you start to type, locations that match are
    listed. You can also click *Suggest a location* to see a list of available
    locations in your company

  . In the *Display*, select the Free/Busy option for this appointment, which
    calendar the appointment should be added to, and whether this appointment
    should be marked as Private.

  . *Reminder*. Set an alarm notification to remind invitees of the
    appointment.

  . If you configured an email address or SMS alert in your
    *Preferences>Notifications* page, check the appropriate box, *Email* or
    *SMS*.  If you have not configured a notification, click *Configure* to go
    to the *<<_setting_email_and_sms_reminder_notification,,Notifications>>*
    page to set this up.

  . In the text box below Scheduler, type an email message that is included in
    the appointment invitation. To add attachments, click the paperclip icon on
    the toolbar.

  . The default is to ask the attendees to reply to your invitation. If you do
    not want a response from the attendees, in the appointment toolbar, click
    *Options>Request Response* to remove the check mark.

  . If you do not want to send the invite out at this time, click
    *Save*. Otherwise click *Send*.

== Quick Appointments from the Mini Calendar

  * Right click on the mini-calendar and select *New Appointment* or *New All
    Day Appointment*. The QuickAdd Appointment dialog box opens.

== Using Email Messages to Set Up Meetings

You can quickly create a meeting request by dragging and dropping a message,
conversation to a date on the mini-calendar. When you drag and drop a
message or conversation, the information in the message is used to populate
many of the fields on the Appointment page.

  . Click a specific message or conversation and drag it to a date on the
    mini-calendar.

  . The Add Attendees dialog opens The appointment page opens with many of the
    fields populated from information in the message.

    * The Subject of the appointment is the subject of the message.

    * The attendees are all the email addresses in the To: and Cc: fields of the
      message, or the most recent message in conversations. When you drag a
      contact from your contacts lists the mini-calendar, the contact's first
      email address is added to the attendee field.

    * The text of the message becomes the text of the invitation. Message
      attachments are not attached to the appointment request.

  . In the appointment page, review the meeting request details and make any
    necessary changes.

  . Set the time for the meeting, and, if this meeting recurs, set any
    recurrence.

  . Click *Send*.

== Create a Meeting Request From a Contact

  . Click on a name from your *Contacts>Contact lists* address book and drag the
    name to a date on the mini-calendar. The appointment page opens with the
    contact name in the Attendees field.

  . Enter the subject, location, time, and other attendees. if this meeting
    recurs, set any recurrence.

  . Click *OK* to send the invitation.

== Scheduling an Appointment Within an Email Message

Within an email message, certain text is interpreted as a date and triggers
the ability to right-click to create an appointment. Text such as "today",
"tomorrow", a day of the week (i.e. "Thursday"), or an exact date are
highlighted in messages.

  . Hover the mouse over this type of text to see if you have an appointment
    scheduled.

  . Click on the highlighted text to open your calendar.

  . Create the appointment.

== Creating an Appointment from an Existing Appointment

You can create appointment similar to an existing appointment and the
existing attendees, location, notes and recurrent pattern can be quickly set
up for new dates and times. You can also modify any of the information
before sending the invite.

  . Right-click on the appointment to copy and select *Create a Copy*. The
    appointment compose page opens with all the information of the copied
    meeting added to the appointment page.

  . To create an appointment exactly as the one you copied, but on another date,
    you only need to change the start and end date.

  . Make any other changes to attendees, location, text, etc.

  . Click *Send* and a invite is sent to attendees and the appointment is added
    to your calendar.

== Using the Scheduling Tool to View Location Availability

The Calendar scheduling tool can assist you with finding the next-available
free times and meeting locations across your organization. You can set up
preferences for preferred meeting times, buildings, location and room size.

As you enter attendee names, the scheduling tool begins to suggest times and
locations in the Overview pane. You also have the option to look for a
location for your meeting before adding attendees. If you set up your
location preferences, only these locations are displayed.

=== Using the Scheduling Tool to Set Location Preferences

If you always want to reserve rooms that are in a specific location, you can
use the Suggested Location tool in the Calendar application to suggest the
availability of those rooms when you create an appointment.

  . In the *New Appointment* page, click *Suggest a location*.

  . In the pane that opens, click the gear icon.

  . In the *Suggestion Preferences* dialog box, Location Preferences section
    enter the information about the location. You can enter just the name of the
    location, or you can be more specific.

  . Click *OK*.

The column on the right displays locations that meet your requirements. Room
locations are displayed if they have been configured in the company
directory.

Once you set this up for an appointment, this information is saved and
available when you make other appointments.

== Using the Scheduling Tool to Find Attendee Availability

When you schedule meetings, you can check to see when attendees are busy or
free so you can find a good time for all attendees to meet. As you add
attendees to the Attendees field, a suggestion panel in the Overview pane
shows availability in 30 minute time slots for the attendees.

The default time preference is to suggest time within your working hours and
within the attendee’s working hours.

  * Only include my working hours. This is the work week and hours you set in
    your Calendar preferences.

  * Only include other attendee’s working hours. When searching for a location
    it takes into consideration everyone’s working hours.

You can change this.

  . In the *New Appointment* page, click *Suggest a time*.

  . In the *Suggest Times* pane that opens, click the gear icon.

  . Deselect the boxes you do not want used to calculate attendee availability.

  . If is a recurring meeting, select how many instance of the recurring meeting
    an attendee should be available.

  . Click *OK*.

=== View Availability in the Mini-Calendar

The mini-calendar suggests attendee availability by color code.

  * Green in the calendar are the days that all attendees and at least one
    location is available.

  * Red means more than half of the attendees cannot attend the meeting on those
    days.

== Scheduling Equipment

When you set up a meeting and schedule equipment for use in the meeting, you
select the equipment and “invite” it to the meeting. The equipment resource
account receives the invite and if it is free, accepts the meeting.

Administrators set up equipment accounts and configure the equipment’s
scheduling policy. A meeting can be declined if the equipment already has a
meeting scheduled for that time. In some cases, the equipment scheduling
policy is set up to allow the equipment to accept dates in recurring
meetings even if there are conflicts. You receive an email showing which
dates conflict.

== Configure Your Default Meeting Duration

If most of the meetings you schedule are for the same period of time, you
can set this in your preferences. When you set the start time, the end time
is automatically set based on the setting.

  * Go to *Preferences>Calendar* and in the *Default appointment duration*
    drop-down menu select the number of minutes your meetings usually run.

== Changing an Appointment or Meeting

You can change meeting or appointment information. If you created a
recurring meeting, you can change one occurrence or the series of meetings.

You can select to send or not send an email to attendees to update the
meeting details.

  . Double-click on the meeting that you want to change.
+
If the meeting is recurring, the *Open Recurring Item* dialog opens.
+
You can change either a single instance of a recurring meeting or the entire
series.

  . Click *OK* to open the *Appointment* page.

  . Change any information necessary.

  . The default is to ask the attendees to reply to your invitation. If you do
    not want a response from the attendees, in the Calendar toolbar, click
    *Options>Request Response* to remove the check mark.

  . Click *Send* to send the revised meeting details to the attendees.

== Move All Day Events to a New Day

  * To change the date for an all day event, in the Calendar view select the
    event and drag it to the new date.

== Forward a Meeting Invite

You can forward invite emails you receive.

  . In Calendar view, select the appointment to forward

  . Right-click the appointment and select Instance or Series, and select
    *Forward Instance*.

  . In the email that opens, enter the forwarding addresses, add any comments to
    the Compose text area and click *Send*.

== Resend an Meeting Invitation

As the organizer of a meeting you can resend a meeting invitation.

  * In Calendar view, right-click a meeting that you organized and select
    *Re-invite Attendees*. The invitation is immediately re-sent to all
    attendees.

== Cancelling a Meeting

If you created a meeting, you can cancel it. If you created a recurring
meeting, you can delete one occurrence or the entire series. An email is
sent to attendees to inform them of the cancelled meeting. Deleting a
meeting is permanent; you cannot undo the deletion.

[NOTE]
Only the originator of an appointment can cancel the appointment. Attendees
can remove the appointment from their own calendars, but they cannot cancel
the entire appointment.

  . In the calendar view, right-click the meeting and select *Cancel*. A
    confirmation box appears.

  . Click *Edit Message* to edit the email sent to attendees. Click *Send* to
    send the cancellation message.

The appointment is immediately removed from your calendar. An email is sent
to the attendees, and the appointment is deleted from their calendars.

== Delete One Meeting in a Series

  . Right-click on the appointment and select *Instance*.

  . Select *Delete Instance*.

  . When deleting an instance, click *Edit Message* to edit the email sent to
    attendees. Click *Send* to send the cancellation message.

The appointment is immediately removed from your calendar. An email is sent
to the attendees, and the appointment is deleted from their calendars.

== Delete All Meetings in a Series

  . Right-click on the appointment and select *Series*.

  . Select *Delete Series*.

  . Select either to delete all occurrences of the meeting from your calendar
    (both past dates and future dates) or to delete all references from this
    date and future dates. Click *Yes*.

  . Click *Edit Message* to edit the email sent to attendees. Click *Send* to
    send the cancellation message.

The appointment is immediately removed from your calendar. An email is sent
to the attendees, and the appointment is deleted from their calendars. You
cannot undo a delete.

== Printing an Appointment or Meeting

You can print the appointment details.

  . Open the appointment.

  . Click the *Print* icon on the toolbar.

  . Click *OK*.

== Send Invites to Attendees in Different Time Zones

If the time zone is displayed in the appointment page, it reflects the time
zone that you are in. You usually do not need to change this. When you
schedule meetings with attendees in different time zones, the invitation is
sent reflecting the meeting time in their time zone. For example, if you
create a meeting with attendees in California and New York, the invitation
displays Pacific time for attendees in California and Eastern time (three
hours later) for attendees in New York.

== Send Your Free/busy Status to Others

You can email a link of your free/busy status that shows appointments in
your personal and shared calendars.

  . Click the Calendar tab.

  . In the Calendar Overview pane, click the gear icon.

  . Click *Send Free & Busy Link* As and select to send the information as
    either *HTML*, *ICS*, or an *ICS Event*.

  . In the *Compose Email* page that opens complete the address and subject
    line. The calendar link is in the text area. Add more information if you
    want.

  . Click *Send* to send the email to the users.

The recipients can click the link to view your schedule. Your calendar
updates itself for the recipients when you add new events to your calendars.

== Display Your Free/Busy Information

The free/busy feature allows others to see meeting times scheduled on your
calendars. The free/busy feature is on by default, but you can turn it off
or limit who can see the information.

  . Go to the *Preferences>Calendar* page.

  . Scroll to the *Permissions* section, select the *Free/Busy* option that you
    want to set for this calendar.
+
If you select *Allow only the following internal users to see my free/busy
information*, in the text field enter the email address of the internal
users.

  . (Optional) In the *Invites* section, specify who can invite you to meetings.
+
If you select *Allow only the following internal users to see my free/busy
information*, in the text field, enter their internal user names or full
email address.

  . If you limit who can invite you to meetings, you might want to select *Send
    to send an auto-reply to users who are denied from inviting me*.

  . Click *Save*.

[NOTE]
These settings do not affect calendars that you have configured to not
display free/busy information.

== Responding to a Meeting Invitation

Invitations to meetings are delivered to your Inbox, and if you have the
Calendar preferences *General>Default appointment visibility>Automatically
add received appointments to calendar* enabled, the meeting is also added to
your default Calendar and marked New.

You can respond to the invitation either from the Inbox or from the Calendar
pane.

  . Open the message that contains the meeting request in either Inbox or
    right-click the appointment in the Calendar.

  . Select whether you want to accept or decline the meeting. If you want to
    propose a new time, the meeting organizer receives an email with the
    suggested time.

A reply is automatically sent to the meeting organizer.

After you respond to the meeting invitation, the invitation is moved to the
Trash, and *New* is removed from the calendar notice.

Declined appointments display on your calendar in a faded view, as a
reminder of the meetings you declined. You can delete the declined meetings
any time.

== Setting Email and SMS Reminder Notification

You can set up to have appointment and task reminders sent to you through
email and as a text message to your mobile device.  The reminder is sent
according to the Reminder time that is configured in the task or
appointment.

[NOTE]
You can set notification up when you are working in a task or calendar page
and click *Configure*.  A notification you set up or change from a task or
calendar page, changes the address or phone number in the
*Preferences>Notifications* page. A notification is then sent to you about
the upcoming task or calendar even. You cannot set up different notification
address or SMS number for different tasks and calendar items.

=== Set up Email Notification

  . Go to *Preferences>Notifications*.

  . Enter the email address that should be sent the reminder.

  . Click *Save*.

=== Set up SMS Notification

  . Go to *Preferences>Notifications*.

  . Select your country from the *Region* drop-down menu.

  . Select your phone carrier from the *Carrier* drop-down menu.

  . Enter your phone number in the *Phone Number* field.

  . Click *Send Verification Code*.  A text message is sent to your phone.

  . Enter the code you received in the message in the *Verification Code* field.

  . Click *Validate Code*. The Status field shows the confirmed number.

  . Click *Save*.

== Automatically add received appointments to calendar.

Email invitations sent to your Inbox can be automatically added to your
calendar. You can accept or decline the invite from either the Inbox or
Calendar.

When this option is not checked, the appointment is added to your calendar
when you click Accept or Tentative in the message.

  . Go to the *Preferences>Calendar* page.

  . In the *General* section select *Automatically add received appointments to
    calendar*.

  . Click *Save*.

== Show reminders

You can set up meeting reminders. The default is five minutes. You can also
choose to *Play a sound* with the reminder. If your computer volume is set
to mute, you will not hear a sound. Select *Flash the browser title* if you
are working in a different browser tab or browser window and choose to have
the browser title flash to remind you.

  . Go to the *Preferences>Calendar* page.

  . In the *General>Show Reminders* section, set how many minutes before
    meetings to send you a reminder. This is the default and you can change it
    for individual meetings.

  . Select how you want to be notified about an upcoming meeting. Select any of
    these options.
+
[cols="1,2a", options="header"]
|=======================================================================
|Option |Description

|Play a sound |

You are notified by a beep. If you have your volume set to mute, you do not
hear a sound. For this to work, you must have either QuickTime or Windows
MediaCenter installed.

|Flash the browser title |

You are notified by the browser title flashing.

|Show a popup notification |

Information about the message displays. You must have Yahoo!BrowserPlus
installed.

To get a copy, go to
http://browserplus.yahoo.com/

|=======================================================================

== Hide Declined Meetings in Your Calendar

When you decline a meeting, the meeting continue to display on your calendar
in a faded view. You can set your preferences so that meetings you decline
do not display in your calendar.

  . Go the *Preferences>Calendar* page, in the General section deselect *Show
    declined meetings*.

  . Click *Save*.
