= Using Mail Filters

== Working with Email Filters

You can define filters to manage incoming and outgoing email messages,
including Calendar-related messages and setting up the Activity Stream
filter to manage less important messages. A filter consists of one or more
conditions and one or more actions. A condition can be based on a subject,
from a specific person, or messages for a particular date. If the message
matches the conditions, the specified actions are performed.

You can create filters to do the following:

  * Sort incoming messages into folders. For example, all email messages from
    your supervisor are automatically moved into your Management Directives
    folder upon receipt.

  * Tag messages. For example, email messages from the corporate-events mailing
    list is marked with the Events tag.

  * Forward or discard email. For example, all email messages received from a
    particular email address is moved to the Trash folder.

  * Sort sent messages into specific topic-related folders.

  * Flag messages for importance.

Filters are applied in the order that they are listed. You can change the
order at any time.

[NOTE]

An email message is evaluated by each active filter, unless you specify that
a message is treated only by the first filter that it matches. Usually, you
do not want other filters applied to a message once there is a match because
the message can undergo multiple, perhaps contradictory, actions.

=== Setting Up Filter Rules

Filter rules consists of one or more conditions and one or more actions. If
the message matches the conditions, the specified actions are performed.

You can also set Activity Stream rules. Activity Stream rules are set to
move less important messages out of your Inbox and into an Activity Stream
folder that you can check at your convenience.

== Creating a Filter

You can define filters to manage incoming and outgoing email messages. A
filter consists of one or more conditions and one or more actions. If the
message matches the conditions, the specified actions are performed.

  . Go to the *Preferences>Filters* page.

  . Click either *Incoming Message Filters* or *Outgoing Message Filters*.

  . Select *Create Filter*.

  . In the *Filter Name* text box, enter a unique name for the filter.

  . To make the filter active, check the *Active* box in the upper right corner.

  . Select whether the message must meet any or all the listed conditions.

    * *any* means that if a message meets any one of the conditions, the
      action is performed.

    * *all* means that the message must meet all of the conditions for the
      action to be performed.

  . From the drop-down menu, select which part of the message to apply to the
    filter, such as the *Subject* or *From* field.

  . Select how the item must match, such as *contains* or *matches exactly*.

  . Enter or select the information to compare against such as the date, email
    address, or phrase. Conditions are not case-sensitive.
+
For example, if you selected *Subject* and *contains*, and entered *Staff
Meeting*, all messages containing Staff Meeting are filtered. The filter
also catches Staff Meetings or Today’s Staff Meeting because you chose
*contains* and not *matches exactly*.

  . (Optional) To add more conditions, click the *+* button and repeat the above
    steps. The order of the conditions does not matter.

  . Under *Perform the following actions*, select an action from the drop-down
    menu.
+
Depending on the action that you select, you might need to browse to locate
a folder or tag name.

  . (Optional) To add more actions, click the *+* button and repeat the above
    step. The actions are applied in the order in which they are listed.

  . The default is to stop looking for matching filters after the first
    match. If you want more than one filter to be applied to a message, deselect
    *Do not process additional filters*.

[NOTE]

Usually, you do not want other filters applied to a message once there is a
match because the message can undergo multiple, perhaps contradictory,
actions.

  . When you are done creating the filter, click *OK*.

== Creating a Filter from an Email Message

You can create a filter based on an email message in your Inbox. The filter
information is extracted from the message, and you can then modify the
conditions and actions.

  * Right-click an email message and select *Create Filter*.
+
The Add Filter dialog box appears populated with the information from the
email message.

  . In the *Filter Name* text box, type a unique name for the filter.

  . Change the conditions and actions as necessary using the drop-down menus.

  . Click *OK*.

== Creating a Filter for Calendar Invitations

You can create a filter to organize Calendar invitations you receive. You
can filter invitations that you receive and invitations that you send. You
can set this filter to act on

  . Go to the *Preferences>Filters* page.

  . Click either *Incoming Message Filters* or *Outgoing Message Filters*.

  . Select *Create Filter*.

  . In the *Filter Name* text box, enter a unique name for the filter.

  . To make the filter active, check the *Active* box in the upper right corner.

  . In the *Subject* drop-down menu, select *Calendar*.

  . Select an *invite is replied/not reply* or *invite is requested/not
    requested* condition from the drop-down menu.

  . (Optional) To add more conditions, click the *+* button and repeat the above
    steps. The order of the conditions does not matter.

 . Under *Perform the following actions* select an action from the drop-down
   menu, such as moving an invitation to a specific folder.
+
Depending on the action that you select, you might need to browse to locate
a folder or tag name.

  . (Optional) To add more actions, click the + button and repeat the above
    step. The actions are applied in the order in which they are listed.

  . The default is to stop looking for matching filters after the first
    match. If you want more than one filter to be applied to a message, deselect
    *Do not process additional filters*.

  . Click *OK*.

== Making a Filter Active or Inactive

You can turn a filter on or off. If a filter is inactive, it is
ignored. Making a filter inactive allows you to keep it for later use rather
than deleting it.

  . Go to the *Preferences>Filters* page.

  . Click *Edit Filter*.

  . Deselect the *Active* box in the upper right corner to turn the filter off.

  . Click *OK*.

== Filter Conditions

A filter can contain one or more conditions. For example, if someone sends
you email messages from more than one email address and you want to direct
all messages from the person into one folder, you can create one filter that
has two conditions, one for each email address, and one action to move the
email messages to the same folder.

The order of the conditions is not important. You can select whether the
email message must match all conditions or just meet any one of the listed
conditions. You can also use a negative condition. For example, you can
filter an email message that does not contain a particular word. Filter
conditions are not case-sensitive.

A filter condition can be based on the following:

  * Specific email addresses in the From, To, or Cc fields

  * Email messages that are under or over a specific size

  * Dates

  * Presence or absence of file attachments

  * Words in the message subject or body

  * Calendar invitation

=== Filtering Using _Any_ Versus _All_

Conditions within a filter rule can be grouped using *Any* or *All*. The use
of these terms is similar to the "AND" versus "OR" type searches described
under the Search feature, with *Any* being OR and *All* being AND.

If you select *Any* when defining conditions for a new filter rule, then a
message that meets any one of the conditions is considered a match. However,
if you select *All*, every condition specified in that filter rule must
apply in order for that message to match the filter.

=== Filtering Using Contains, Matches, and Is options

Three of the comparison methods for filter conditions are Contains, Matches
pattern, and Matches Exactly. These options appear for some items such as
the subject line.

  * *Contains* means that the specified line must contain, somewhere within
    it, the specified string. For example, specifying that the subject line
    contains "bananas" would match both "Cooking with bananas" and "Bananas
    for breakfast".

  * *Matches* pattern means that the specified line must match the
    specified string, which includes wildcards. For example, specifying "
    bana*" would match "banana" and "banana tree" but not "free bananas".

  * *Is* means that the specified line must exactly match the specified
    string, with no wildcards or substitutions. For example, specifying
    that the subject line must match "bananas" would only match "bananas"
    and not "Banana", "My bananas", or "Bananas?"

== Filter Conditions and Actions Supported

Filter rules are case insensitive, meaning that the rules ignore
capitalization.

=== Conditions

Comparison fields include the following:

  * *From*. Use this to specify a name in the From: header of an email
    message.

  * *To*. Same as From, but looks for specified names in the To: header.

  * *Cc*. Same as From, but looks in the Cc: header.

  * *To or Cc*. Same as From, but looks in both To and Cc header.

  * *Subject*. Looks in the message's Subject header.

  * *Size*. Use this to select email messages that are larger or smaller
    than a specified size. The size of the email includes any file
    attachments. You can use this to discard email messages that are too
    large.

  * *Date*. Use this option to specify email messages sent before or after
    a specified date.

  * *Body*. The options for Body are Contains/Does not contain, and you can
    specify matching words in the body of the email. You cannot filter for
    words in file attachments.

  * *Read receipt*. Read receipt messages can be filtered.

  * *Attachment*. Filter for email messages that have, or don't have, file
    attachments.

  * *Address In*. Tests for the presence of an address in your
    contacts. The next field allows you to specify which address.

  * *Calendar Invite*. Filter calendar-related messages.

  * *Social*. Filters messages from social networking sites.

  * *Header Named*. When this option is selected, an additional text input
    field appears before the comparison operator (the "contains"
    portion). This option allows you to specify any email header. You can
    specify not only the standard fields of To: or From: but also Date,
    Reply-To, or other custom fields that may be included in the message
    header. You can use this option to filter email messages that have
    "malformed" headers, meaning they do not contain certain information
    that is normally considered standard for an email message. Sometimes
    spam, which is automatically generated, omits information such as the
    Sender or Reply-To fields. Use the second text field (the field
    immediately to the right of the comparison operator) to specify the
    header to test for.

=== Actions

  * *Keep in Inbox*. Saves mail to Inbox. If none of the filter rules match
    an email message, this action takes place by default.

  * *File into folder*. Moves the mail to a specified folder.

  * *Discard*. Deletes the mail message without delivering it. The message
    is not in any of your folders, not even Trash.

  * *Forward*. Forwards mail to the address you specify.

  * *Mark*. Select as Read or as Flagged.

  * *Tag with*. You can tag matching messages with a selected tag.

=== Multiple Actions

You can create a filter rule made up of multiple actions. The combinations
of actions in your rule are interpreted as follows:

  * *Discard*. If combined with other actions, discard is ignored and the
    other actions take place.

  * *File into folder*. Multiple "file into" actions results in multiple
    copies of the message being stored in different folders. If a specified
    folder does not exist, the message is saved to the Inbox.

  * *Tag/Mark*. These actions apply to the message returned from the nearest
    preceding action.

  * *Keep in Inbox*. Multiple "keep" actions can be specified, but only one
    copy of the message is saved to the Inbox.

  * *Forward to address*. Mail is forwarded to the address specified.

== Filter Rule Actions

A filter rule can contain one or more actions. If the email message matches
the specified conditions, all actions are applied in the order in which they
appear in the filter.

Filter rule actions can include the following:

  * Move the message to a specific folder

  * Tag or flag the message

  * Discard the message before it reaches your Inbox

  * Forward the message to a specified email address

The *Do not process additional filters* action should be the last action
within each filter rule. This prevents the application of any additional
filter rules to email messages that match the current rule. If it is not
specified, subsequent filter rules are evaluated for the mail message, even
if the current filter is a match. You probably do not want to have the same
message match more than one filter rule and undergo multiple, perhaps
contradictory actions.

== Filtering Using Wildcards

Wildcards can be used in comparisons that use the "Matches pattern"
comparison operator. The two wildcard characters are * and ?

=== Asterisk (*)

The asterisk * is a placeholder for "zero or more characters of any type".

Example subject-line search string: banana*float

With Matches: Subject lines such as " bananafloat", "bananas", "banana-leaf
casserole float" but not "super-banana-float"

Example subject-line search string: w*bandanna

With Matches: Subject lines such as "white bandanna" or "whose bandanna" but
not "whose bandanna is this?"

=== Question mark (?)

The question mark is a placeholder for "exactly one character".

Example subject-line search string: banana?boat

With Matches: Subject lines such as " bananasboat", "banana-boat",
"banana!boat", or "banana boat"

=== Escape character is Slash: \

There may be times that you will want to specify an exact match on a string
that contains characters that normally are considered wildcards. For
example, you might want to specify a match on a subject line where the main
heading is surrounded on both sides by three asterisks, such as

`\*\**MORE MONEY!!!**\*` or `\**\*FREE GIFT***`

To specify a wildcard as itself rather than a substitution for other
characters, use the backslash \ immediately before the character. For
example the comparison string `"\\*\*\\**\*\\*\*"` specifies a subject with
three asterisks before and after any string in the middle (including
spaces).

== Viewing Filters

=== Viewing Existing Filters

You can view the filters that you have defined and their status.

  . Go to the *Preferences>Filters* page.

   . To view information about a particular filter, double-click it.

=== Viewing Filter Order

Active filters are applied in the order that they are listed. You can change
the order.

  . Go to the *Preferences>Filters* page.

  . Use the Move Up and Move Down buttons to change the order.

[NOTE]
An email message is evaluated by each active filter unless you specify that
a message is treated only by the first filter that it matches. Usually, you
do not want other filters applied to a message once there is a match because
the message can undergo multiple, perhaps contradictory, actions.

== Editing a Filter

You can modify an existing filter.

  . Go to the *Preferences>Filters* page.

  . Select the filter that you want to change.

  . Click *Edit Filter*.

  . Change the conditions and actions as necessary using the drop-down menus.

  . Click *OK*.

== Applying a Filter

You can apply a filter to email messages that you have already
received. Using a filter is a quick way to organize email by moving messages
into folders.

  . Go to the *Preferences>Filters* page.

  . Click *Run Filter*.

  . Select the folders to apply the filter.

  . Click *OK*.
