= Working in Briefcase

== Working in Briefcase

Briefcase can be used to share and manage documents that you create in
Briefcase or documents and images that you upload to your Briefcase
folders. Use Briefcase to save files in your account so that you can access
these files whenever you log in to your account from any computer.

You can share your briefcases folders with others who can view and edit the
files in the shared Briefcase.

You can create multiple briefcase folders and then upload any type of file
from your computer or your computer network, save attachments sent with your
email messages, and create new documents.

Files in Briefcase are copies of the original file, whether the file is on
your computer or an attachment to your email. Changes you make to files in
your briefcase do not change the original file.

=== Creating Briefcase Folders

  . Go to *Briefcase Folders*.

  . Click the *gear icon* and select *New Briefcase*.

  . Enter a *Name* for the new briefcase folder.
+
The briefcase folder name must be unique within the hierarchy of your all of
mailbox folders. This name cannot match any top-level folder in your
mailbox, calendar, or address book. For example, if you have a calendar
named Holidays, you cannot name a top-level briefcase Holidays. Holidays
could be a name of a briefcase within another briefcase.

  . Select the *Color* of the new briefcase file.

  . Select the folder hierarchy, either under Folders or under another briefcase
    folder. You can create a new top-level briefcase, or you can place it under
    an existing briefcase.

  . Click *OK*.

=== Upload Files from Briefcase

  . Go to the *Briefcase* tab and select the Briefcase to save the file.

  . Click *Upload File* and *Browse* to find the file to upload.

  . In the *Notes* text field, add any information about the file. This
    information is displayed in the file list.

  . To add another file, click *Add*.
+
You cannot upload a file with the same name to the same briefcase. If a file
is uploaded that already exists in the folder, an Upload Conflict dialog
displays. You can either click *Yes* to upload the file, overwriting the
existing file, or click *No*.
+
The version number is updated if a file is overwritten.

  . When all files are uploaded, click *OK*.

[NOTE]
If you selected the wrong briefcase, you can use drag and drop to move the
file to the correct Briefcase folder.

If the file is too large, a warning displays. Files that you upload impact
your account quota.

== Viewing Files in Briefcase

  . Go to the Briefcase page.

  . Click View on the Task toolbar to select how to display the file in the
    Preview Pane.
+
[cols="1,2a", options="header"]
|=======================================================================
|Option |Description

|Preview Pane At The Bottom |

The Briefcase preview pane displays at the bottom of the pane.

|Preview Pane On the Right |

The Briefcase preview pane displays on the right.

|Preview Pane Off |

The Preview Pane does not display

|=======================================================================

== Upload Email Attachments to Briefcase

  . To add the attachment, click the *Briefcase* link in the email message
    header next to the Attachments link.

  . In the *Add to Briefcase* dialog, select the destination folder or create a
    new briefcase folder.

  . Click *OK*.

[NOTE]
A copy of the attachment is put in your Briefcase folder. If you are
managing your quota, you may want to delete the attachment in the email when
you add upload the attachment to your Briefcase.

== Adding Files to Your Briefcase Folders

Uploading a file copies a file from your personal computer to your
account. This makes the file available any time you log into your
account. You can upload files in the following ways:

  * Clicking attachments you receive with your email messages.

  * Using the file upload tool when working in Briefcase

  * Using WebDav Client tools

== Creating Documents in Briefcase

You can create documents in Briefcase and design the content layout using
the rich-text format tools available in Briefcase.

  . Go to the *Briefcase* tab and select the Briefcase folder where you want to
    create a new document.

  . Click *New Document*. A blank page appears:

  . Compose the content of the page using the rich text editor. You can add
    style, color and tables to your page from the toolbar links.

  . Enter the name of the new document in the *Save* field.

  . Click *Save*.

  . Add document version notes if applicable. Click *OK*.

== View Version History of a Briefcase File

Version control lets you manage changes to your documents in Briefcase. Each
time you make a change to a file and save the file, the version number is
updated. The latest version number is displayed in the file document list.

  * Click the arrow in the preview pane to see the version history and the
    authors. If preview pane is turned off, you will see a column with the
    version number.

=== Restore a Document to the Previous Version

  * Right-click on another version and select *Restore as Current Version*.

== Checking Out and Checking In Files to Briefcase

You can open files in your Briefcase any time you log on to your
account. You must have the appropriate software application to open and read
or updated files that you did not create with the documents tools in
Briefcase.

If you have shared a briefcase with others, you may want to use the
check-out and check-in feature of Briefcase to manage editing of files. The
check out and check in process is slightly different depending on whether
the file is one you uploaded to your briefcase or a documented in created in
briefcase

  . Go to the *Briefcase* tab and select the file that you want to check out.

  . Click *Actions>Check Out File*.

  . In the dialog that displays, select to save the file to your
    computer. Because you checked out the file, you must save it to your
    computer to edit it, as the file has been marked as read-only and changes to
    the file cannot be saved.

  . Edit the file with the appropriate tool and save it.

  . After you saved the file to your computer, right-click on the locked file
    from the Briefcase file list and select *Check In File*.

  . In the *Check In File to Briefcase* dialog that opens, browse to the edited
    file on your computer. If you want to add information about changes, enter
    this is the *Notes* text area.

  . Click *Check In*. The file is uploaded. The lock is removed and the file
    details, including a new version number and notes, are updated in the file
    list.

== Sending Files from Your Briefcase

While working in Briefcase folders, you can send a link to files in your
Briefcase and you can send the actual file as an attachment to email
messages. The recipients must have the appropriate software to open the
files.

=== Send an Email with a Link to a File

You can send an email that has a link to a file in briefcase. The recipient
must have appropriate share permission to work with the file and the
appropriate software to open the file. Any modifications they make to a
linked file are reflected in the file in your Briefcase folder.

  . Go to the *Briefcase* tab and select the file to share.

  . Click *Actions* and select *Send link(s)*. A confirmation dialog opens
    reminding you that the recipient must have permission to view the content of
    the folder. Click *Yes* to proceed.

  . A new compose email message opens with the link displayed in the body of the
    message. Complete the email message and click *Send* to mail the message.

=== Send a File as an Email Attachment

You can send a file as an attachment to an email directly from
Briefcase. The recipients must have the appropriate software to open the
file.

  . Go to the *Briefcase* tab and select the file to attach.

  . Click *Actions* and select *Send as attachment(s)*. The email compose page
    opens with the file attached.

  . Add the recipient’s email address and complete the email message.

  . Click *Send*.

== Rename a File

Renaming a file creates another version of the file.

  . Go to the *Briefcase* tab and select the document you want to rename.

  . Right-click on the file and select *Rename*. The Name field is changed to an
    editable field.

  . Edit this field to change the file name. Remember to keep the same extension
    in the file name or it may not be editable later.

  . Press *Enter*.

== Move Files in Briefcase

You can move files from one briefcase to another.

  . Go to the *Briefcase* tab.

  . Right-click the file you want to move.

  . Click *Move* and select the destination folder or create a new briefcase
    folder.

  . Click *OK*.

== Delete a Document from Briefcase

  . Go to the *Briefcase* tab and select the document you want to delete.

  . Click *Delete*. Each version of a file counts against your account quota.
